### PR TITLE
Update LayarKacaProvider.kt

### PR DESCRIPTION
**Pull request by adityajd**
update domain nontondrama

### CODE REVIEW

**Comment by IndusAryan** [comment]
holy f'king  sheet man, can't you do everything in one pull request, your interviewer of HR will consider this as bad practice not as some high PR count

**Comment by IndusAryan** [comment]
10 prs for domain change and other 10 for gradle version update, it takes so much time for the merger to review every pr and then cancel worklfows

**Comment by adityajd** [comment]
> man, you should do everything in one pull request, your interviewer or HR - recruiter will consider this as bad practice, not as some high PR count
> 10 prs for domain change and other 10 for gradle version update, it takes so much time for the merger to review every pr and then cancel worklfows

Sorry sir, I only do it using my cellphone, next time I will make just one request

**Comment by adityajd** [comment]
> man, you should do everything in one pull request, your interviewer or HR - recruiter will consider this as bad practice, not as some high PR count
> 10 prs for domain change and other 10 for gradle version update, it takes so much time for the merger to review every pr and then cancel worklfows

Sorry sir, I only do it using my cellphone, next time I will make just one request

**Comment by IndusAryan** [comment]
create a new branch and then change domains and gradle version and commit and the PR
after that review that pr if anything is wrong like missing quotation then you can push another commit on same branch in your fork, that will automatically add in the PR

**Pull request closed without merging**
